import { useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { Button } from '../components';
import { Link } from 'react-router-dom';
import { submitEnquiry } from '../services/enquiries';

const newKey = () => globalThis.crypto?.randomUUID?.() || `enquiry-${Date.now()}`;
const initial = { name: '', email: '', phone: '', organization: '', subject: '', message: '', eventType: '', eventDate: '', guestCount: '', location: '', budgetRange: '', requirements: '', country: '', pathway: '', contributionRange: '', resources: '', timeline: '', notes: '', consent: false };

function FormShell({ title, eyebrow, children, onSubmit, error, busy, success, successCopy }) {
  if (success) return <main className="page confirmation-page"><div className="success-card"><div className="confirmation-icon"><Check size={30} /></div><span className="eyebrow">{eyebrow} recorded</span><h1>{title}</h1><p>{successCopy}</p><Link className="button button-primary" to="/">Return to Tchow</Link></div></main>;
  return <main className="page form-page"><div className="form-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>Complete the details below. Your information is saved securely after the server validates it.</p></div><form className="wide-form" onSubmit={onSubmit} noValidate>{children}{error && <p className="form-error" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy ? 'Saving...' : 'Submit enquiry'} <ArrowRight size={17} /></Button></form></main>;
}

function useEnquiry(kind) {
  const [form, setForm] = useState(initial); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(false); const [key] = useState(newKey);
  const change = (event) => { const { name, value, checked, type } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); setError(''); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError('');
    const data = { ...form, consentVersion: 'v1' };
    if (kind === 'contact') { if (!form.name || !form.email || !form.subject || !form.message || !form.consent) { setError('Please complete the required fields and consent checkbox.'); setBusy(false); return; } }
    if (kind === 'catering') { if (!form.name || !form.email || !form.phone || !form.eventType || !form.eventDate || !form.guestCount || !form.location || !form.consent) { setError('Please complete the required event details and consent checkbox.'); setBusy(false); return; } }
    if (kind === 'partnership') { if (!form.name || !form.email || !form.phone || !form.country || !form.pathway || !form.contributionRange || !form.timeline || !form.resources || !form.consent) { setError('Please complete the required partnership details and consent checkbox.'); setBusy(false); return; } }
    try { await submitEnquiry(kind, data, key); setSuccess(true); } catch (e) { setError(e.message || 'We could not save this enquiry. Please try again.'); } finally { setBusy(false); }
  };
  return { form, change, submit, error, busy, success };
}

export function DatabaseContact() { const x = useEnquiry('contact'); return <FormShell eyebrow="The Tchow concierge" title="Let’s make something worth gathering for." {...x} successCopy="Your contact enquiry has been recorded. We will use the details to guide the next conversation; email delivery is not represented until configured."><div className="form-grid"><label>Full name<input name="name" value={x.form.name} onChange={x.change} required /></label><label>Email address<input name="email" type="email" value={x.form.email} onChange={x.change} required /></label><label>Phone number<input name="phone" value={x.form.phone} onChange={x.change} /></label><label>Subject<input name="subject" value={x.form.subject} onChange={x.change} required /></label><label className="span-2">Message<textarea name="message" rows="6" value={x.form.message} onChange={x.change} required /></label><label className="checkbox span-2"><input name="consent" type="checkbox" checked={x.form.consent} onChange={x.change} required /> I consent to Tchow storing this enquiry to respond to it.</label></div></FormShell>; }

export function DatabaseCatering() { const x = useEnquiry('catering'); return <FormShell eyebrow="Corporate and private catering" title="Tell us what you are planning." {...x} successCopy="Your catering enquiry has been recorded. The team workflow will be connected to its configured notification provider separately."><div className="form-grid">{[['name','Full name'],['organization','Organization'],['email','Email address'],['phone','Phone number'],['eventType','Event type'],['eventDate','Event date'],['guestCount','Guest count'],['location','Location'],['budgetRange','Budget range']].map(([name,label]) => <label key={name}>{label}<input name={name} type={name === 'email' ? 'email' : name === 'eventDate' ? 'date' : name === 'guestCount' ? 'number' : 'text'} min={name === 'guestCount' ? 1 : undefined} value={x.form[name]} onChange={x.change} required={!['organization','budgetRange'].includes(name)} /></label>)}<label className="span-2">Additional requirements<textarea name="requirements" rows="5" value={x.form.requirements} onChange={x.change} /></label><label className="checkbox span-2"><input name="consent" type="checkbox" checked={x.form.consent} onChange={x.change} required /> I consent to Tchow storing these event details.</label></div></FormShell>; }

export function DatabasePartnership() { const x = useEnquiry('partnership'); return <FormShell eyebrow="Partnership Interest Application" title="Start a thoughtful conversation." {...x} successCopy="Your partnership interest has been recorded in this frontend preview. Formal review and communication workflows will be connected after the backend is implemented."><div className="form-grid">{[['name','Full name'],['email','Email address'],['phone','Phone or WhatsApp number'],['organization','Organization'],['country','Country'],['pathway','Preferred partnership pathway'],['contributionRange','Expected capital or contribution range'],['timeline','Partnership timeline']].map(([name,label]) => <label key={name}>{label}<input name={name} type={name === 'email' ? 'email' : 'text'} value={x.form[name]} onChange={x.change} required={!['organization'].includes(name)} /></label>)}<label className="span-2">Strategic skills or resources<textarea name="resources" rows="4" value={x.form.resources} onChange={x.change} required /></label><label className="span-2">Additional notes<textarea name="notes" rows="4" value={x.form.notes} onChange={x.change} /></label><label className="checkbox span-2"><input name="consent" type="checkbox" checked={x.form.consent} onChange={x.change} required /> I understand this is partnership interest only, not an offer, payment, or guarantee.</label></div></FormShell>; }
