import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const headers = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization,content-type,apikey,x-client-info' };
const out = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...headers, 'Content-Type': 'application/json' } });
const json = async (response: Response) => { try { return await response.json(); } catch { return {}; } };
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers }); if (req.method !== 'POST') return out({ error: { code: 'method_not_allowed' } }, 405);
  const url = Deno.env.get('SUPABASE_URL'); const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); const paystackKey = Deno.env.get('PAYSTACK_SECRET_KEY'); if (!url || !serviceKey || !paystackKey) return out({ error: { code: 'server_not_configured' } }, 503);
  const token = req.headers.get('Authorization')?.replace(/^Bearer\s+/i, ''); const admin = createClient(url, serviceKey, { auth: { persistSession: false } }); const actor = token ? (await admin.auth.getUser(token)).data.user : null; if (!actor) return out({ error: { code: 'unauthorized' } }, 401);
  let body: any; try { body = await req.json(); } catch { return out({ error: { code: 'invalid_json' } }, 400); }
  const financeRoles = ['owner', 'finance', 'manager'];
  const staff = await admin.from('staff_members').select('user_id,role,is_active,staff_permissions!inner(permission)').eq('user_id', actor.id).eq('is_active', true).eq('staff_permissions.permission', 'manage_payments').maybeSingle(); if (staff.error) return out({ error: { code: 'authorization_unavailable' } }, 503); if (!staff.data || !financeRoles.includes(staff.data.role)) return out({ error: { code: 'forbidden' } }, 403);
  if (!body.orderId || !body.idempotencyKey || !Number.isInteger(body.amountKobo)) return out({ error: { code: 'invalid_request' } }, 422);
  const reserved = await admin.rpc('request_order_refund', { p_order_id: body.orderId, p_amount_kobo: body.amountKobo, p_reason: body.reason, p_idempotency_key: body.idempotencyKey, p_actor_id: actor.id }); if (reserved.error) return out({ error: { code: 'refund_rejected', message: reserved.error.message } }, 409); const result = reserved.data;
  if (result.duplicate) return out({ result });
  const payment = await admin.from('verified_transactions').select('provider_reference,amount_kobo,currency').eq('id', result.transactionId).maybeSingle();
  if (payment.error || !payment.data) { await admin.rpc('apply_refund_provider_result', { p_refund_id: result.refundId, p_status: 'failed', p_provider_refund_reference: null, p_provider_status: 'not_found', p_failure_reason: 'verified_transaction_unavailable' }); return out({ error: { code: 'refund_unavailable' } }, 409); }
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10000); let response: Response;
  try { response = await fetch('https://api.paystack.co/refund', { method: 'POST', headers: { Authorization: `Bearer ${paystackKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ transaction: payment.data.provider_reference, amount: result.amountKobo, currency: payment.data.currency, customer_note: 'Tchow refund', merchant_note: body.reason }), signal: controller.signal }); } catch (error) { clearTimeout(timeout); if ((error as Error).name === 'AbortError') return out({ result: { ...result, status: 'pending', message: 'Provider response is pending reconciliation.' } }, 202); await admin.rpc('apply_refund_provider_result', { p_refund_id: result.refundId, p_status: 'failed', p_provider_refund_reference: null, p_provider_status: 'request_failed', p_failure_reason: 'provider_request_failed' }); return out({ error: { code: 'provider_failed' } }, 502); } finally { clearTimeout(timeout); }
  const provider = await json(response); if (!response.ok || !provider.status) { await admin.rpc('apply_refund_provider_result', { p_refund_id: result.refundId, p_status: 'failed', p_provider_refund_reference: null, p_provider_status: provider.message || 'rejected', p_failure_reason: 'provider_rejected' }); return out({ error: { code: 'provider_rejected' } }, 502); }
  const applied = await admin.rpc('apply_refund_provider_result', { p_refund_id: result.refundId, p_status: provider.data?.status === 'processed' ? 'successful' : 'pending', p_provider_refund_reference: provider.data?.id ? String(provider.data.id) : null, p_provider_status: provider.data?.status || 'pending', p_failure_reason: null }); if (applied.error) return out({ error: { code: 'refund_recording_failed' } }, 500);
  return out({ result: applied.data }, applied.data?.status === 'successful' ? 200 : 202);
});
