import { useEffect } from 'react';
import { ArrowRight, Check, X } from 'lucide-react';

export const formatNaira = (value) => `₦${Number(value || 0).toLocaleString('en-NG')}`;

export function Header({ cartCount = 0 }) {
  return <header className="site-header"><a className="wordmark" href="/" aria-label="Tchow home">TCHOW<span>.</span></a><nav aria-label="Main navigation"><a href="/menu">Menu</a><a href="/build-your-box">Build Your Box</a><a href="/catering">Catering</a><a href="/about">About</a><a href="/investors">Investor Relations</a><a href="/contact">Contact</a></nav><a className="header-cart" href="/cart" aria-label={`Cart, ${cartCount} items`}>Cart <span>{cartCount}</span></a></header>;
}

export function Footer() {
  return <footer className="site-footer"><div><a className="wordmark" href="/">TCHOW<span>.</span></a><p>Food experiences made memorable.</p></div><div className="footer-links"><a href="/menu">Menu</a><a href="/catering">Catering</a><a href="/contact">Contact</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a></div></footer>;
}

export function Button({ children, variant = 'primary', className = '', ...props }) { return <button className={`button button-${variant} ${className}`.trim()} {...props}>{children}</button>; }
export function ProductCard({ product, onAdd, href = `/menu/${product?.id}` }) { return <article className="product-card"><a href={href}><img src={product.image} alt={product.name} /><span className="eyebrow">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p></a><div className="product-card-footer"><strong>{formatNaira(product.price)}</strong><Button onClick={() => onAdd?.(product)}>Add</Button></div></article>; }
export function ProductGrid({ products = [], onAdd, empty = 'No products found.' }) { if (!products.length) return <EmptyState title={empty} />; return <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} onAdd={onAdd} />)}</div>; }
export function CategoryTabs({ categories = [], active, onChange }) { return <div className="category-tabs" role="tablist" aria-label="Product categories">{categories.map((category) => <button key={category} role="tab" aria-selected={active === category} className={active === category ? 'active' : ''} onClick={() => onChange?.(category)}>{category}</button>)}</div>; }
export function SearchBar({ value, onChange, placeholder = 'Search the menu' }) { return <label className="search-bar"><span className="sr-only">Search</span><input value={value} onChange={(e) => onChange?.(e.target.value)} placeholder={placeholder} /></label>; }
export function FilterDrawer({ open, onClose, children, title = 'Filters' }) { if (!open) return null; return <div className="drawer-overlay" onClick={onClose}><aside className="drawer-panel" role="dialog" aria-modal="true" aria-labelledby="filter-title" onClick={(e) => e.stopPropagation()}><button className="drawer-close" onClick={onClose} aria-label="Close filters"><X size={20}/></button><h2 id="filter-title">{title}</h2>{children}</aside></div>; }
export function CartItem({ item, onUpdate, onRemove }) { return <article className="cart-item"><img src={item.image} alt="" /><div><h3>{item.name}</h3><small>{formatNaira(item.price)} each</small></div><QuantitySelector value={item.quantity} onChange={(value) => onUpdate?.(item.id, value)} /><strong>{formatNaira(item.price * item.quantity)}</strong><button className="icon-button" onClick={() => onRemove?.(item.id)} aria-label={`Remove ${item.name}`}><X size={16}/></button></article>; }
export function PriceSummary({ subtotal = 0, delivery = 0, total = subtotal + delivery }) { return <dl className="price-summary"><div><dt>Subtotal</dt><dd>{formatNaira(subtotal)}</dd></div><div><dt>Delivery estimate</dt><dd>{delivery ? formatNaira(delivery) : 'To be confirmed'}</dd></div><div className="price-total"><dt>Total</dt><dd>{formatNaira(total)}</dd></div></dl>; }
export function QuantitySelector({ value = 1, onChange }) { return <div className="quantity-selector" aria-label="Quantity"><button onClick={() => onChange?.(Math.max(1, value - 1))} aria-label="Decrease quantity">-</button><span>{value}</span><button onClick={() => onChange?.(value + 1)} aria-label="Increase quantity">+</button></div>; }
export function Modal({ open, onClose, title, children }) { useEffect(() => { if (!open) return undefined; const close = (e) => e.key === 'Escape' && onClose?.(); document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [open, onClose]); if (!open) return null; return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={(e) => e.stopPropagation()}><button className="drawer-close" onClick={onClose} aria-label="Close dialog"><X size={20}/></button><h2 id="modal-title">{title}</h2>{children}</section></div>; }
export function Drawer({ open, onClose, title, children }) { return open ? <FilterDrawer open onClose={onClose} title={title}>{children}</FilterDrawer> : null; }
export function Toast({ message, onClose }) { if (!message) return null; return <div className="toast" role="status"><Check size={16}/>{message}{onClose && <button onClick={onClose} aria-label="Dismiss notification"><X size={14}/></button>}</div>; }
export function FormField({ label, error, ...props }) { return <label className="form-field">{label}<input aria-invalid={Boolean(error)} {...props} />{error && <small className="field-error">{error}</small>}</label>; }
export function SelectField({ label, options = [], error, ...props }) { return <label className="form-field">{label}<select aria-invalid={Boolean(error)} {...props}>{options.map((option) => <option key={option.value ?? option} value={option.value ?? option}>{option.label ?? option}</option>)}</select>{error && <small className="field-error">{error}</small>}</label>; }
export function TextareaField({ label, error, ...props }) { return <label className="form-field">{label}<textarea aria-invalid={Boolean(error)} {...props} />{error && <small className="field-error">{error}</small>}</label>; }
export function StatusBadge({ status }) { return <span className={`status-badge status-${String(status).toLowerCase().replaceAll(' ', '-')}`}>{status}</span>; }
export function EmptyState({ title = 'Nothing here yet.', message, children }) { return <div className="empty-state"><span className="eyebrow">Tchow</span><h2>{title}</h2>{message && <p>{message}</p>}{children}</div>; }
export function LoadingState({ message = 'Loading...' }) { return <div className="loading-state" role="status"><span className="loading-dot" />{message}</div>; }
export function ErrorState({ message = 'Something went wrong.', onRetry }) { return <div className="error-state" role="alert"><h2>We hit a small pause.</h2><p>{message}</p>{onRetry && <Button onClick={onRetry}>Try again</Button>}</div>; }
export function Breadcrumbs({ items = [] }) { return <nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((item, index) => <span key={item.label}>{index > 0 && <span aria-hidden="true"> / </span>}{index === items.length - 1 ? <strong>{item.label}</strong> : <a href={item.href}>{item.label}</a>}</span>)}</nav>; }
export function PageHero({ eyebrow, title, children, actions }) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children && <p>{children}</p>}{actions && <div className="hero-actions">{actions}</div>}</section>; }
export function SectionHeading({ eyebrow, title, children }) { return <div className="section-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{children}</div>; }
export function ConfirmationDialog({ open, onClose, onConfirm, title = 'Are you sure?', children = 'This action cannot be undone.' }) { return <Modal open={open} onClose={onClose} title={title}><p>{children}</p><div className="modal-actions"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={onConfirm}>Confirm</Button></div></Modal>; }
export function DataTable({ columns = [], rows = [], rowKey = 'id', empty = 'No records found.' }) { if (!rows.length) return <EmptyState title={empty} />; return <div className="data-table-wrap"><table className="data-table"><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[rowKey] ?? index}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : row[column.key]}</td>)}</tr>)}</tbody></table></div>; }
export function AdminSidebar({ active }) { const links = [['dashboard', 'Overview', '/admin'], ['orders', 'Orders', '/admin/orders'], ['menu', 'Menu', '/admin/menu'], ['catering', 'Catering', '/admin/catering'], ['investors', 'Partnerships', '/admin/investors'], ['settings', 'Settings', '/admin/settings']]; return <aside className="admin-sidebar"><div className="wordmark">TCHOW<span>.</span></div><span className="admin-label">Operations preview</span>{links.map(([key, label, href]) => <a key={key} href={href} className={active === key ? 'active' : ''}>{label}</a>)}<a href="/">Exit preview <ArrowRight size={14}/></a></aside>; }
