import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const headers = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'content-type,apikey,authorization,x-client-info,idempotency-key' };
const out = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...headers, 'Content-Type': 'application/json' } });
const limits: Record<string, number> = { contact: 5, catering: 3, partnership: 2 };
const text = (v: unknown, max: number) => typeof v === 'string' && v.trim().length <= max ? v.trim() : null;
const email = (v: unknown) => typeof v === 'string' && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v) && v.length <= 320 ? v.trim().toLowerCase() : null;
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers });
  if (req.method !== 'POST') return out({ error: { code: 'method_not_allowed' } }, 405);
  const url = Deno.env.get('SUPABASE_URL'); const key = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if (!url || !key) return out({ error: { code: 'server_not_configured' } }, 503);
  let body: any; try { body = await req.json(); } catch { return out({ error: { code: 'invalid_json' } }, 400); }
  const kind = body.kind; const data = body.data || {}; const idem = req.headers.get('idempotency-key') || body.idempotencyKey; if (!limits[kind] || !idem || String(idem).length > 200) return out({ error: { code: 'invalid_submission' } }, 422);
  const common = { name: text(data.name, 160), email: email(data.email), phone: text(data.phone, 40) }; if (!common.name || !common.email) return out({ error: { code: 'invalid_contact_details' } }, 422);
  if (kind === 'contact' && (!text(data.subject, 180) || !text(data.message, 10000) || !data.consent)) return out({ error: { code: 'invalid_contact_submission' } }, 422);
  if (kind === 'catering' && (!common.phone || !text(data.eventType, 160) || !/^\d{4}-\d{2}-\d{2}$/.test(data.eventDate) || !Number.isInteger(Number(data.guestCount)) || Number(data.guestCount) < 1 || Number(data.guestCount) > 100000 || !text(data.location, 500) || !data.consent)) return out({ error: { code: 'invalid_catering_submission' } }, 422);
  if (kind === 'partnership' && (!common.phone || !text(data.country, 100) || !text(data.pathway, 160) || !text(data.contributionRange, 160) || !text(data.resources, 10000) || !text(data.timeline, 160) || !data.consent)) return out({ error: { code: 'invalid_partnership_submission' } }, 422);
  const admin = createClient(url, key, { auth: { persistSession: false } }); const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown'; const bucket = `${kind}:${ip}`; const limit = await admin.from('enquiry_rate_limits').select('*').eq('bucket', bucket).maybeSingle(); if (limit.error) return out({ error: { code: 'rate_limit_unavailable' } }, 503);
  const now = Date.now(); const active = limit.data && now - new Date(limit.data.window_started_at).getTime() < 3600000; if (active && limit.data.submission_count >= limits[kind]) return out({ error: { code: 'rate_limited', message: 'Please try again later.' } }, 429); const rate = await admin.from('enquiry_rate_limits').upsert({ bucket, window_started_at: active ? limit.data.window_started_at : new Date().toISOString(), submission_count: active ? limit.data.submission_count + 1 : 1 }); if (rate.error) return out({ error: { code: 'rate_limit_unavailable' } }, 503);
  const base = { idempotency_key: idem, full_name: common.name, email: common.email, phone: common.phone } as any; let table = ''; let payload: any = base;
  if (kind === 'contact') { table = 'contact_enquiries'; payload = { ...base, subject: text(data.subject, 180), message: text(data.message, 10000) }; }
  if (kind === 'catering') { table = 'catering_enquiries'; payload = { ...base, organization: text(data.organization, 200), event_type: text(data.eventType, 160), event_date: data.eventDate, guest_count: Number(data.guestCount), location: text(data.location, 500), budget_range: text(data.budgetRange, 160), additional_requirements: text(data.requirements, 10000) }; }
  if (kind === 'partnership') { table = 'partnership_applications'; payload = { ...base, organization: text(data.organization, 200), country: text(data.country, 100), pathway: text(data.pathway, 160), contribution_range: text(data.contributionRange, 160), strategic_resources: text(data.resources, 10000), timeline: text(data.timeline, 160), additional_notes: text(data.notes, 10000), consent_version: text(data.consentVersion, 30) || 'v1', consent_at: new Date().toISOString() }; }
  const inserted = await admin.from(table).insert(payload).select('id,status,created_at').single(); if (inserted.error?.code === '23505') return out({ received: true, duplicate: true }); if (inserted.error) return out({ error: { code: 'persistence_failed', message: 'The enquiry could not be recorded.' } }, 500);
  const queued = await admin.from('notification_outbox').insert({ channel: 'internal', event_type: `${kind}_enquiry_created`, recipient: 'operations', payload: { table, recordId: inserted.data.id }, idempotency_key: `enquiry:${kind}:${idem}` }); if (queued.error && queued.error.code !== '23505') console.error('notification enqueue failed', queued.error.code);
  return out({ received: true, record: inserted.data });
});
