import { useEffect, useState } from 'react';
import { verifyPayment } from '../services/payments';

export function PaymentStatus() {
  const reference = new URLSearchParams(location.search).get('reference') || '';
  const [state, setState] = useState({ loading: true, kind: 'checking', message: 'Checking payment status…', attempts: 0 });
  useEffect(() => {
    if (!reference) { setState({ loading: false, kind: 'error', message: 'No payment reference was provided.', attempts: 0 }); return undefined; }
    let active = true; let timer; let attempts = 0; const maxAttempts = 12;
    const check = async () => { attempts += 1; try { const result = await verifyPayment(reference); if (!active) return; const payment = result.payment || {}; if (payment.outcome === 'paid') { localStorage.removeItem('tchow-cart'); window.dispatchEvent(new Event('tchow-cart-updated')); setState({ loading: false, kind: 'paid', message: 'Payment verified. Your order is now being reviewed.', attempts }); } else if (payment.outcome === 'failed') setState({ loading: false, kind: 'failed', message: 'Paystack reported that this payment failed. You can retry from checkout.', attempts }); else if (payment.outcome === 'abandoned') setState({ loading: false, kind: 'abandoned', message: 'This payment was abandoned before completion. You can retry from checkout.', attempts }); else if (payment.outcome === 'exception' || payment.outcome === 'duplicate') setState({ loading: false, kind: 'exception', message: payment.reason === 'second_successful_payment' ? 'A second successful payment needs manual review. No duplicate fulfilment was created.' : 'This payment needs manual review before the order can proceed.', attempts }); else if (attempts >= maxAttempts) setState({ loading: false, kind: 'pending', message: 'Payment is still pending. Retry verification later or contact Tchow support.', attempts }); else { setState({ loading: true, kind: 'pending', message: 'Payment is still pending. Checking again shortly…', attempts }); timer = setTimeout(check, 5000); } } catch { if (active && attempts >= maxAttempts) setState({ loading: false, kind: 'pending', message: 'Verification timed out. Retry verification or contact Tchow support.', attempts }); else if (active) { setState({ loading: true, kind: 'pending', message: 'Verification is still pending. Checking again shortly…', attempts }); timer = setTimeout(check, 5000); } } };
    check();
    return () => { active = false; clearTimeout(timer); };
  }, [reference]);
  return <main className="page"><div className="intro"><span className="eyebrow">Payment status</span><h1>{state.loading ? 'We are checking your payment.' : 'Payment update'}</h1><p>{state.message}</p>{state.loading && <p className="summary-note">Verification attempt {state.attempts} of 12.</p>}{!state.loading && state.kind !== 'paid' && <p><a className="button button-outline" href="/checkout">Retry payment</a> <a className="text-link" href="/contact">Contact support</a></p>}<p className="summary-note">Payment status is confirmed only by the server. Do not rely on a browser callback alone.</p></div></main>;
}
