import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components';
import { getAdminSettings, updateAdminSettings } from '../services/settings';

export function DatabaseAdminSettings() {
  const [settings, setSettings] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getAdminSettings().then((result) => setSettings(Object.fromEntries((result.public || []).map((x) => [x.key, typeof x.value === 'string' ? x.value : JSON.stringify(x.value)])))).catch((e) => setError(e.message || 'Unable to load settings.')).finally(() => setLoading(false)); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { await updateAdminSettings(settings); setMessage('Settings saved to the database.'); } catch (e) { setError(e.message || 'Settings could not be saved.'); } finally { setSaving(false); } };
  return <main className="admin-page"><aside className="admin-sidebar"><div className="wordmark">TCHOW<span>.</span></div><span className="admin-label">Operations</span><Link to="/admin">Overview</Link><Link to="/admin/orders">Orders</Link><Link to="/admin/menu">Menu</Link><Link to="/admin/catering">Catering</Link><Link to="/admin/investors">Partnerships</Link><Link to="/admin/settings" className="active">Settings</Link><Link to="/">Exit</Link></aside><div className="admin-workspace"><header className="admin-topbar"><div><span className="eyebrow">Internal operations</span><strong>Business settings</strong></div><span className="mock-pill">Live database</span></header><div className="admin-content"><div className="admin-banner"><span className="eyebrow">Authorized settings</span><strong>Secrets and provider credentials are not editable here.</strong></div>{loading ? <p className="muted">Loading settings...</p> : <form className="wide-form" onSubmit={save}><div className="form-grid">{['brand_name','contact_email','catering_email','partnership_email','operating_hours','delivery_message','homepage_announcement'].map((key) => <label key={key}>{key.replaceAll('_', ' ')}<input value={settings[key] || ''} onChange={(e) => setSettings({ ...settings, [key]: e.target.value })} /></label>)}</div>{message && <p role="status" className="form-success">{message}</p>}{error && <p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save settings'}</Button></form>}</div></div></main>;
}
