import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components';
import { getAdminSettings, publishAdminSettings, updateAdminSettings } from '../services/settings';

const fields = [['brand_name', 'Brand name'], ['contact_email', 'Contact email'], ['catering_email', 'Catering email'], ['partnership_email', 'Partnership email'], ['operating_hours', 'Operating hours'], ['delivery_message', 'Delivery message'], ['homepage_announcement', 'Homepage announcement'], ['homepage_featured_product_ids', 'Featured product IDs (JSON array)'], ['social_links', 'Social links (JSON object)']];
const structured = new Set(['homepage_featured_product_ids', 'social_links']);
const display = (key, value) => typeof value === 'string' ? value : JSON.stringify(value ?? (key === 'social_links' ? {} : []), null, 2);
const parse = (key, value) => structured.has(key) ? JSON.parse(value) : value;

export function DatabaseAdminSettings() {
  const [settings, setSettings] = useState({}); const [drafts, setDrafts] = useState({}); const [published, setPublished] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => { setLoading(true); getAdminSettings().then((result) => { const records = result.public || []; const values = Object.fromEntries(records.map((item) => [item.key, item.value])); setSettings(values); setDrafts(Object.fromEntries(fields.map(([key]) => [key, display(key, values[key])] ))); setPublished(Object.fromEntries(fields.map(([key]) => [key, Boolean(records.find((item) => item.key === key)?.is_published)]))); }).catch((e) => setError(e.message || 'Unable to load settings.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const update = (key, value) => { setMessage(''); setError(''); setDrafts((current) => ({ ...current, [key]: value })); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { const nextSettings = Object.fromEntries(fields.filter(([key]) => drafts[key] !== '').map(([key]) => [key, parse(key, drafts[key])])); const result = await updateAdminSettings(nextSettings, Object.keys(published).filter((key) => published[key] && nextSettings[key] !== undefined)); setMessage(`Saved ${result.updated?.length || 0} settings.`); load(); } catch (e) { setError(e.message || 'Settings could not be saved.'); } finally { setSaving(false); } };
  const togglePublication = async (key) => { if (drafts[key] === undefined || drafts[key] === '') { setError('Save this setting before publishing it.'); return; } setSaving(true); setMessage(''); setError(''); try { await publishAdminSettings([key], !published[key]); setPublished((current) => ({ ...current, [key]: !current[key] })); setMessage(`${key.replaceAll('_', ' ')} ${published[key] ? 'is now a draft.' : 'is now published.'}`); } catch (e) { setError(e.message || 'Publication change could not be saved.'); } finally { setSaving(false); } };
  return <main className="admin-page"><aside className="admin-sidebar"><div className="wordmark">TCHOW<span>.</span></div><span className="admin-label">Operations</span><Link to="/admin">Overview</Link><Link to="/admin/orders">Orders</Link><Link to="/admin/menu">Menu</Link><Link to="/admin/catering">Catering</Link><Link to="/admin/investors">Partnerships</Link><Link to="/admin/settings" className="active">Settings</Link><Link to="/">Exit</Link></aside><div className="admin-workspace"><header className="admin-topbar"><div><span className="eyebrow">Internal operations</span><strong>Business settings</strong></div><span className="mock-pill">Live database</span></header><div className="admin-content"><div className="admin-banner"><span className="eyebrow">Authorized settings</span><strong>Draft and published states are controlled separately.</strong></div>{loading ? <p className="muted">Loading settings...</p> : <form className="wide-form" onSubmit={save}><div className="form-grid">{fields.map(([key, label]) => <label key={key}>{label}{structured.has(key) ? <textarea rows="4" value={drafts[key] ?? ''} onChange={(e) => update(key, e.target.value)} /> : <input type={key.includes('email') ? 'email' : 'text'} value={drafts[key] ?? ''} onChange={(e) => update(key, e.target.value)} />}<small>{published[key] ? 'Published publicly' : 'Draft only'}</small>{!key.includes('email') && <button type="button" className="text-link" onClick={() => togglePublication(key)} disabled={saving || drafts[key] === undefined}>{published[key] ? 'Unpublish' : 'Publish'}</button>}</label>)}</div>{message && <p role="status" className="form-success">{message}</p>}{error && <p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save drafts and changes'}</Button></form>}</div></div></main>;
}
