import { useEffect, useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { useAuth } from './AuthContext';
import { addressRepository, orderRepository, profileRepository } from '../services/repositories';

const formatAmount = (kobo = 0) => `₦${Math.round(kobo / 100).toLocaleString('en-NG')}`;
const load = (setter, action) => action().then((data) => setter({ loading: false, data, error: '' })).catch((error) => setter({ loading: false, data: null, error: error.message || 'Could not load your account.' }));

export function AccountHome() {
  const { user, signOut } = useAuth();
  const [profile, setProfile] = useState({ loading: true, data: null, error: '' });
  const [orders, setOrders] = useState({ loading: true, data: [], error: '' });
  useEffect(() => { load(setProfile, profileRepository.get); load(setOrders, async () => (await orderRepository.list({ pageSize: 3 })).data || []); }, []);
  return <main className="page account-page"><div className="account-header"><div><span className="eyebrow">Your account</span><h1>Hello, {profile.data?.full_name || user?.email?.split('@')[0] || 'there'}.</h1><p>{user?.email}</p></div><nav className="account-nav"><a href="/account">Overview</a><a href="/account/orders">Orders</a><a href="/account/profile">Profile</a><button className="text-link" onClick={() => signOut()}>Sign out</button></nav></div><div className="account-dashboard"><div className="account-card account-welcome"><span className="eyebrow">Account summary</span><h2>Ready for your next table?</h2><p>Your account data is securely connected to Supabase.</p><a className="button" href="/menu">Explore the menu <ArrowRight size={17}/></a></div><div className="account-card"><span className="eyebrow">Recent orders</span>{orders.loading ? <p>Loading orders...</p> : orders.data?.length ? orders.data.map((order) => <p key={order.id}><strong>{order.order_number}</strong><br/>{order.status} · {formatAmount(order.total_kobo)}</p>) : <p>No orders yet.</p>}<a className="text-link" href="/account/orders">View all orders <ArrowRight size={15}/></a></div><div className="account-card"><span className="eyebrow">Saved delivery details</span><h3>Keep an address ready</h3><p>Manage delivery addresses from your profile.</p><a className="text-link" href="/account/profile">Edit profile <ArrowRight size={15}/></a></div></div>{profile.error && <p className="form-error" role="alert">{profile.error}</p>}</main>;
}

export function AccountOrders() {
  const [result, setResult] = useState({ loading: true, data: [], error: '' });
  useEffect(() => { load(setResult, async () => (await orderRepository.list()).data || []); }, []);
  return <main className="page orders-page"><div className="account-header"><div><span className="eyebrow">Your account / orders</span><h1>Order history.</h1><p>Orders are retrieved securely from your account.</p></div><a className="text-link" href="/account">Back to account</a></div>{result.loading ? <div className="loading-state">Loading your orders...</div> : result.error ? <p className="form-error" role="alert">{result.error}</p> : <div className="orders-list">{result.data.length ? result.data.map((order) => <article className="order-card" key={order.id}><div><strong>{order.order_number}</strong><span>{new Date(order.created_at).toLocaleDateString('en-NG')}</span></div><p>{order.order_items?.map((item) => `${item.quantity} × ${item.product_name_snapshot}`).join(', ') || 'Order items'}</p><strong>{formatAmount(order.total_kobo)}</strong><span className="status-badge">{order.status}</span><a className="text-link" href={`/account/orders/${order.id}`}>View order</a></article>) : <div className="empty-state"><h2>No orders yet.</h2><p>Your completed orders will appear here.</p><a className="button" href="/menu">Explore the menu</a></div>}</div>}</main>;
}

export function AccountProfile() {
  const { user } = useAuth();
  const [profile, setProfile] = useState({ full_name: '', phone: '', preferred_communication: 'Email', dietary_notes: '' });
  const [addresses, setAddresses] = useState([]);
  const [address, setAddress] = useState({ label: 'Default', recipient_name: '', phone: '', address_line: '', area: '', city: 'Lagos', state: 'Lagos', delivery_instructions: '', is_default: true });
  const [state, setState] = useState({ loading: true, error: '', saved: false });
  useEffect(() => { Promise.all([profileRepository.get(), addressRepository.list()]).then(([savedProfile, savedAddresses]) => { setProfile({ full_name: savedProfile.full_name || '', phone: savedProfile.phone || '', preferred_communication: savedProfile.preferred_communication || 'Email', dietary_notes: savedProfile.dietary_notes || '' }); setAddresses(savedAddresses || []); setState({ loading: false, error: '', saved: false }); }).catch((error) => setState({ loading: false, error: error.message || 'Could not load your profile.', saved: false })); }, []);
  const save = async (event) => { event.preventDefault(); setState({ loading: true, error: '', saved: false }); try { await profileRepository.update(profile); if (address.address_line && address.recipient_name && address.phone && address.area) { const savedAddress = await addressRepository.save({ ...address, user_id: user.id }); setAddresses((current) => [savedAddress, ...current.filter((item) => item.id !== savedAddress.id)]); } setState({ loading: false, error: '', saved: true }); } catch (error) { setState({ loading: false, error: error.message || 'Could not save your profile.', saved: false }); } };
  return <main className="page form-page"><div className="account-header"><div><span className="eyebrow">Your account / profile</span><h1>Your details, your way.</h1><p>Profile data is stored in your Supabase account.</p></div><a className="text-link" href="/account">Back to account</a></div><form className="wide-form profile-form" onSubmit={save} noValidate><div className="form-grid"><label>Full name<input required value={profile.full_name} onChange={(e) => setProfile({ ...profile, full_name: e.target.value })} /></label><label>Email address<input value={user?.email || ''} placeholder="Managed by Supabase Auth" disabled /></label><label>Phone number<input required value={profile.phone} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} /></label><label>Preferred communication<select value={profile.preferred_communication} onChange={(e) => setProfile({ ...profile, preferred_communication: e.target.value })}><option>Email</option><option>Phone</option><option>WhatsApp</option></select></label><label className="span-2">Dietary notes<textarea rows="4" value={profile.dietary_notes} onChange={(e) => setProfile({ ...profile, dietary_notes: e.target.value })} /></label></div><span className="eyebrow checkout-eyebrow">Saved delivery addresses</span>{addresses.map((item) => <div className="saved-address" key={item.id}><strong>{item.label}</strong><span>{item.address_line}, {item.area}, {item.city}</span></div>)}<div className="form-grid"><label>Address label<input value={address.label} onChange={(e) => setAddress({ ...address, label: e.target.value })} /></label><label>Recipient name<input value={address.recipient_name} onChange={(e) => setAddress({ ...address, recipient_name: e.target.value })} /></label><label>Address<input value={address.address_line} onChange={(e) => setAddress({ ...address, address_line: e.target.value })} /></label><label>Area<input value={address.area} onChange={(e) => setAddress({ ...address, area: e.target.value })} /></label><label>City<input value={address.city} onChange={(e) => setAddress({ ...address, city: e.target.value })} /></label><label>State<input value={address.state} onChange={(e) => setAddress({ ...address, state: e.target.value })} /></label><label>Address phone<input value={address.phone} onChange={(e) => setAddress({ ...address, phone: e.target.value })} /></label></div>{state.error && <p className="form-error" role="alert">{state.error}</p>}{state.saved && <p className="form-success" role="status"><Check size={15}/> Profile and address saved.</p>}<button className="button" type="submit" disabled={state.loading}>{state.loading ? 'Saving...' : 'Save changes'} <Check size={16}/></button></form></main>;
}
